---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fapi-pep-as
    app.kubernetes.io/component: fapi-pep-as
    app.kubernetes.io/instance: fapi-pep-as
    app.kubernetes.io/part-of: pingid
    tier: middle
  name: fapi-pep-as
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fapi-pep-as
      app.kubernetes.io/component: fapi-pep-as
      app.kubernetes.io/instance: fapi-pep-as
      app.kubernetes.io/part-of: pingid
      tier: middle
  template:
    metadata:
      labels:
        app: fapi-pep-as
        app.kubernetes.io/component: fapi-pep-as
        app.kubernetes.io/instance: fapi-pep-as
        app.kubernetes.io/part-of: pingid
        tier: middle
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - secretRef:
                name: as-sapig-secrets
            - configMapRef:
                name: as-sapig-deployment-config
          image: fapi-pep-as
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /kube/liveness
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          name: fapi-pep-as
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /kube/readiness
              port: 8080
            initialDelaySeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/ig/secrets/truststore
              name: new-truststore
              readOnly: true
      initContainers:
        - command:
            - /home/forgerock/import-pem-certs.sh
          env:
            - name: TRUSTSTORE_PATH
              value: /truststore/igtruststore
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: IG_TRUSTSTORE_PASSWORD
                  name: as-sapig-secrets
            - name: IG_PEM_TRUSTSTORE
              value: /var/run/secrets/truststore/ig-truststore.pem
          image: fapi-pep-as
          imagePullPolicy: Always
          name: truststore-init
          volumeMounts:
            - mountPath: /truststore
              name: new-truststore
            - mountPath: /var/run/secrets/truststore
              name: ig-truststore-pem
      securityContext:
        runAsGroup: 0
        runAsUser: 11111
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Exists
      volumes:
        - emptyDir: {}
          name: new-truststore
        - name: ig-truststore-pem
          secret:
            optional: false
            secretName: ig-truststore-pem